sudo: required

language: go

services:
  - docker

os:
  - linux

go:
  - 1.8

before_install:
  - go get -u github.com/kardianos/govendor

script:
  - make build

notifications:
    slack: mkfsn:YEmUQn2zG3wS4btZZ8KgMy4V

branches:
  only:
  - master
